<a href="https://colab.research.google.com/github/Nikita-khadse/Wome_cloth_prediction/blob/main/cloth_revenue_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
# @title **Women Cloth Reviews Prediction with Multi Nomial Naive Bayes** { display-mode: "form" }

**The multimonial Naive Bayes Classifier is suitable for classification with discrete feature(e.g., word counts for text classification).The multinomial distribution normally require integer features countes. However, in practice,fractional counts such as if-idf may also work.**

In [73]:
# @title **Import Library**

In [74]:
import pandas as pd

In [75]:
import numpy as np

In [76]:
import matplotlib.pyplot as plt

In [77]:
import seaborn as sns

In [78]:
# @title **Import Dataset**

In [79]:
df = pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Teaching-Data/main/Women%20Clothing%20E-Commerce%20Review.csv')

In [80]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [82]:
df.shape

(23486, 10)

In [83]:
# @title **Missing Value**

**Remove the missing values in the reviews columns with no review text**

In [84]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [85]:
df[df['Review']==""]=np.NaN

In [86]:
df['Review'].fillna("No Review",inplace=True)

In [87]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [88]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

In [89]:
# @title **Define Target (y) and Feature(X)**

In [90]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [91]:
X = df['Review']

In [92]:
y = df['Review']

In [93]:
Y = df['Rating']

In [94]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [95]:
# @title **Train Test Split**

In [96]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size = 0.7, random_state=2529)

In [97]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [98]:
# @title **Get Feature Text Conversion To Tokens**

In [99]:
from sklearn.feature_extraction.text import CountVectorizer

In [100]:
cv= CountVectorizer(lowercase = True, analyzer='word' , ngram_range=(2,3),stop_words='english',max_features=5000)

In [101]:
X_train = cv.fit_transform(X_train)

In [102]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [103]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [104]:
X_test = cv.fit_transform(X_test)

In [105]:
cv.get_feature_names_out()

array(['10 12', '10 12 took', '10 12 tops', ..., 'years old',
       'yesterday love', 'yoga pants'], dtype=object)

In [106]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [107]:
# @title **Get Model Train**

In [108]:
from sklearn.naive_bayes import MultinomialNB

In [109]:
model = MultinomialNB()

In [110]:
model.fit(X_train,y_train)

MultinomialNB()

In [111]:
# @title **Get Model Prediction**

In [112]:
y_pred = model.predict(X_test)

In [113]:
y_pred.shape

(7046,)

In [114]:
y_pred

array(['No Review', 'No Review', 'No Review', ..., 'No Review',
       'No Review', 'No Review'], dtype='<U508')

In [115]:
# @title **Get Probability Of Each Predicted Class**

In [116]:
model.predict_proba(X_test)

array([[5.95110484e-05, 5.93449657e-05, 6.00122917e-05, ...,
        5.96776293e-05, 6.03489656e-05, 6.06876641e-05],
       [6.02216993e-05, 6.01376075e-05, 6.04747819e-05, ...,
        6.03059254e-05, 6.06441789e-05, 6.08141185e-05],
       [5.99243889e-05, 5.97810149e-05, 6.03567506e-05, ...,
        6.00681355e-05, 6.06468687e-05, 6.09384980e-05],
       ...,
       [5.96291021e-05, 5.94508211e-05, 6.01673752e-05, ...,
        5.98079535e-05, 6.05291019e-05, 6.08931491e-05],
       [5.98740096e-05, 5.97546079e-05, 6.02337923e-05, ...,
        5.99936738e-05, 6.04749683e-05, 6.07172070e-05],
       [6.06725116e-05, 6.06482935e-05, 6.07452531e-05, ...,
        6.06967443e-05, 6.07938202e-05, 6.08424455e-05]])

In [117]:
# @title **Get Model Evaluation**

In [118]:
from sklearn.metrics import confusion_matrix, classification_report

In [119]:
print(confusion_matrix(y_test,y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [120]:
print(classification_report(y_test,y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

In [121]:
# @title **Recategories Ratings as Poor(0) and Good(1)**

In [122]:
df.replace({'Rating' : { 1 : 0, 2 : 0, 3 : 0, 4 : 1, 5 : 1}}, inplace = True)

**Re-Rating as 1,2,3 as 0 and 4,5 as 1**

In [123]:
y = df['Rating']

In [124]:
X = df['Review']

In [125]:
# @title **Train Test Split**

In [126]:
from sklearn.model_selection import train_test_split

In [127]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size = 0.7 ,stratify = y , random_state = 2529)

In [128]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [129]:
# @title **Get Feature Text Conversion To Tokens**

In [130]:
from sklearn.feature_extraction.text import CountVectorizer

In [131]:
cv = CountVectorizer(lowercase = True, analyzer='word',ngram_range=(2, 3), stop_words = 'english', max_features = 5000)

In [132]:
X_train = cv.fit_transform(X_train)

In [133]:
X_test = cv.fit_transform(X_test)

In [134]:
# @title **Get Model Re-Train**

In [135]:
from sklearn.naive_bayes import MultinomialNB

In [136]:
model = MultinomialNB()

In [137]:
model.fit(X_train,y_train)

MultinomialNB()

In [138]:
# @title **Get Model prediction**

In [139]:
y_pred = model.predict(X_test)

In [140]:
y_pred.shape

(7046,)

In [141]:
y_pred

array([1., 1., 1., ..., 1., 1., 1.])

In [142]:
# @title **Get Model Evaluation**

In [143]:
from sklearn.metrics import confusion_matrix, classification_report

In [144]:
print(confusion_matrix(y_test,y_pred))

[[ 449 1134]
 [ 989 4474]]


In [145]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.31      0.28      0.30      1583
         1.0       0.80      0.82      0.81      5463

    accuracy                           0.70      7046
   macro avg       0.56      0.55      0.55      7046
weighted avg       0.69      0.70      0.69      7046

